### ISSUE TITLE
Create index page

### ISSUE THREAD

**Issue by sneakycr0w** [sneakycr0w/lotus#1]
When creating the index page use these requirements:
* Use [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
* Use [animate.css](https://daneden.github.io/animate.css/)
* Use [bootstrap](https://v4-alpha.getbootstrap.com/)

**Comment by zacharysohovich** [comment]
"Wireframe" intialized in ab85a66393cf2b206546f828ee290c39ef7c188d

**Comment by zacharysohovich** [comment]
Angular 2 re-initialized in 2346bf444b6ecbcf0be6f3ffdfa199be7129e28d. CSS Grid **might** not be used in version 1.0.0. I did some tests with it to understand it, but having bootstrap there with its mobile-first functionality might be better for version 1.0.0

**Comment by sneakycr0w** [comment]
Switched from Angular 2 to React. Issue irrelevant
