### ISSUE TITLE
Form Validation in CreateUsersForm

### ISSUE THREAD

**Issue by sneakycr0w** [sneakycr0w/lotus#18]
Right now the CreateUsersForm.jsx has no form validation, so it'll submit no matter what. I'd like it to check if a password is at least 6 characters long, make sure a username is not already taken, and check whether an email is not already taken/is valid.

- [x] Password validator
- [x] Username validator
- [x] Email validator

**Comment by geoffdavis92** [comment]
@sneakycr0w I could take a look at this.

**Comment by sneakycr0w** [comment]
Go for it! Thanks man! You’ll need an instance of mongoDB running to test it.

**Comment by sneakycr0w** [comment]
Any luck @geoffdavis92? I've been digging around some blogs, but haven't found a way that I particularly like doing it. 

I'm trying to do client side first, then server side for more complicated stuff.

**Comment by sneakycr0w** [comment]
Simple form validation added in 6dddea2f71049f72b30e46e2593fc02d8d6c744f
